- hosts: localhost
  connection: local
  #roles:
  # -  osp-setup
  tasks:
##Create FrontEnd Instance
  - name: Create frontend instance
    include_role:
       name: osp-setup
       vars_from: frontend.yaml
###Create App1 server 
  - name: Create app1 instance
    include_role:
       name: osp-setup
       vars_from: app1.yaml
##Create App2 server
  - name: Create app2 instance
    include_role:
       name: osp-setup
       vars_from: app2.yaml
##Create DB server
  - name: Create db instance
    include_role:
       name: osp-setup
       vars_from: db.yaml
